
package com.alsb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-07T23:26:35.552+07:00
 * Generated source version: 3.1.11
 * 
 */
public final class WebService_WebService_Client {

    private static final QName SERVICE_NAME = new QName("http://www.alsb.com/", "WebService");

    private WebService_WebService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = new URL("http://test.osb.vietcapitalbank.com.vn/VCCB_TELLER/ProxyServices/NonFinance?WSDL");//WebService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebService_Service ss = new WebService_Service(wsdlURL, SERVICE_NAME);
        WebService port = ss.getWebService();  
        
        {
        System.out.println("Invoking coreACInterestRateUpdate...");
        java.lang.String _coreACInterestRateUpdate_sourceRef = "_coreACInterestRateUpdate_sourceRef-2116378850";
        java.lang.String _coreACInterestRateUpdate_accountClass = "_coreACInterestRateUpdate_accountClass-1429994470";
        java.lang.String _coreACInterestRateUpdate_ccycd = "_coreACInterestRateUpdate_ccycd295936028";
        java.lang.String _coreACInterestRateUpdate_effectiveDate = "_coreACInterestRateUpdate_effectiveDate-459813933";
        java.lang.String _coreACInterestRateUpdate_brid = "_coreACInterestRateUpdate_brid134514887";
        com.alsb.CoreACInterestRateUpdate.InterestRateList _coreACInterestRateUpdate_interestRateList = new com.alsb.CoreACInterestRateUpdate.InterestRateList();
        java.util.List<com.alsb.CoreACInterestRateUpdate.InterestRateList.InterestRate> _coreACInterestRateUpdate_interestRateListInterestRate = new java.util.ArrayList<com.alsb.CoreACInterestRateUpdate.InterestRateList.InterestRate>();
        com.alsb.CoreACInterestRateUpdate.InterestRateList.InterestRate _coreACInterestRateUpdate_interestRateListInterestRateVal1 = new com.alsb.CoreACInterestRateUpdate.InterestRateList.InterestRate();
        _coreACInterestRateUpdate_interestRateListInterestRateVal1.setParamCode("ParamCode356528258");
        _coreACInterestRateUpdate_interestRateListInterestRateVal1.setInterestRate("InterestRate-1365922528");
        _coreACInterestRateUpdate_interestRateListInterestRateVal1.setInterestRateCode("InterestRateCode1599686009");
        _coreACInterestRateUpdate_interestRateListInterestRate.add(_coreACInterestRateUpdate_interestRateListInterestRateVal1);
        _coreACInterestRateUpdate_interestRateList.getInterestRate().addAll(_coreACInterestRateUpdate_interestRateListInterestRate);
        java.lang.String _coreACInterestRateUpdate_maker = "_coreACInterestRateUpdate_maker-171914528";
        java.lang.String _coreACInterestRateUpdate_approver = "_coreACInterestRateUpdate_approver318212537";
        java.lang.String _coreACInterestRateUpdate__return = port.coreACInterestRateUpdate(_coreACInterestRateUpdate_sourceRef, _coreACInterestRateUpdate_accountClass, _coreACInterestRateUpdate_ccycd, _coreACInterestRateUpdate_effectiveDate, _coreACInterestRateUpdate_brid, _coreACInterestRateUpdate_interestRateList, _coreACInterestRateUpdate_maker, _coreACInterestRateUpdate_approver);
        System.out.println("coreACInterestRateUpdate.result=" + _coreACInterestRateUpdate__return);


        }
        {
        System.out.println("Invoking ldapUserSearch...");
        java.lang.String _ldapUserSearch_userID = "_ldapUserSearch_userID2076219112";
        java.lang.String _ldapUserSearch_name = "_ldapUserSearch_name493752505";
        java.lang.String _ldapUserSearch_username = "_ldapUserSearch_username1688486076";
        java.lang.String _ldapUserSearch_email = "_ldapUserSearch_email694741321";
        com.alsb.LDAPUserSearchResponse.UserList _ldapUserSearch__return = port.ldapUserSearch(_ldapUserSearch_userID, _ldapUserSearch_name, _ldapUserSearch_username, _ldapUserSearch_email);
        System.out.println("ldapUserSearch.result=" + _ldapUserSearch__return);


        }
        {
        System.out.println("Invoking coreUsernameVerify...");
        java.lang.String _coreUsernameVerify_username = "_coreUsernameVerify_username-630255613";
        java.lang.String _coreUsernameVerify_maker = "_coreUsernameVerify_maker-597538297";
        java.lang.String _coreUsernameVerify_approver = "_coreUsernameVerify_approver-2103233687";
        java.lang.String _coreUsernameVerify__return = port.coreUsernameVerify(_coreUsernameVerify_username, _coreUsernameVerify_maker, _coreUsernameVerify_approver);
        System.out.println("coreUsernameVerify.result=" + _coreUsernameVerify__return);


        }
        {
        System.out.println("Invoking coreUserResetPassword...");
        java.lang.String _coreUserResetPassword_sourceRef = "_coreUserResetPassword_sourceRef292166903";
        java.lang.String _coreUserResetPassword_username = "_coreUserResetPassword_username277945677";
        java.lang.String _coreUserResetPassword_newPassword = "_coreUserResetPassword_newPassword1489928255";
        java.lang.String _coreUserResetPassword_maker = "_coreUserResetPassword_maker-391138780";
        java.lang.String _coreUserResetPassword_approver = "_coreUserResetPassword_approver-17053660";
        java.lang.String _coreUserResetPassword__return = port.coreUserResetPassword(_coreUserResetPassword_sourceRef, _coreUserResetPassword_username, _coreUserResetPassword_newPassword, _coreUserResetPassword_maker, _coreUserResetPassword_approver);
        System.out.println("coreUserResetPassword.result=" + _coreUserResetPassword__return);


        }
        {
        System.out.println("Invoking coreACParamsGet...");
        java.lang.String _coreACParamsGet_pACCLASS = "_coreACParamsGet_pACCLASS-1163729535";
        java.lang.String _coreACParamsGet_pMAKERID = "_coreACParamsGet_pMAKERID-527626587";
        java.lang.String _coreACParamsGet_pCHECKERID = "_coreACParamsGet_pCHECKERID1040219663";
        com.alsb.CoreACParamsGetResponse.ParameterList _coreACParamsGet__return = port.coreACParamsGet(_coreACParamsGet_pACCLASS, _coreACParamsGet_pMAKERID, _coreACParamsGet_pCHECKERID);
        System.out.println("coreACParamsGet.result=" + _coreACParamsGet__return);


        }
        {
        System.out.println("Invoking coreACInterestRateSearch...");
        java.lang.String _coreACInterestRateSearch_pACCLASS = "_coreACInterestRateSearch_pACCLASS1076852597";
        java.lang.String _coreACInterestRateSearch_pCCY = "_coreACInterestRateSearch_pCCY2088265233";
        java.lang.String _coreACInterestRateSearch_pEFFECTIVEDATE = "_coreACInterestRateSearch_pEFFECTIVEDATE693932839";
        java.lang.String _coreACInterestRateSearch_pBRANCH = "_coreACInterestRateSearch_pBRANCH-1876001504";
        java.lang.String _coreACInterestRateSearch_pMAKER = "_coreACInterestRateSearch_pMAKER-941045066";
        java.lang.String _coreACInterestRateSearch_pCHECKER = "_coreACInterestRateSearch_pCHECKER-145809095";
        com.alsb.CoreACInterestRateSearchResponse.InterestRateList _coreACInterestRateSearch__return = port.coreACInterestRateSearch(_coreACInterestRateSearch_pACCLASS, _coreACInterestRateSearch_pCCY, _coreACInterestRateSearch_pEFFECTIVEDATE, _coreACInterestRateSearch_pBRANCH, _coreACInterestRateSearch_pMAKER, _coreACInterestRateSearch_pCHECKER);
        System.out.println("coreACInterestRateSearch.result=" + _coreACInterestRateSearch__return);


        }
        {
        System.out.println("Invoking cifCreate...");
        java.lang.String _cifCreate_sourceRef = "_cifCreate_sourceRef-885193500";
        java.lang.String _cifCreate_brid = "_cifCreate_brid1220667485";
        java.lang.String _cifCreate_type = "_cifCreate_type1114429691";
        java.lang.String _cifCreate_fullName = "_cifCreate_fullName-402384559";
        java.lang.String _cifCreate_shortName = "_cifCreate_shortName648621809";
        java.lang.String _cifCreate_gender = "_cifCreate_gender-56121019";
        java.lang.String _cifCreate_dateOfBirth = "_cifCreate_dateOfBirth-1690225912";
        java.lang.String _cifCreate_isEmployee = "_cifCreate_isEmployee1868410210";
        java.lang.String _cifCreate_taxCode = "_cifCreate_taxCode950440793";
        java.lang.String _cifCreate_identityType = "_cifCreate_identityType-1130718575";
        java.lang.String _cifCreate_identityNumber = "_cifCreate_identityNumber-2012338190";
        java.lang.String _cifCreate_issueDate = "_cifCreate_issueDate-46257412";
        java.lang.String _cifCreate_issuePlace = "_cifCreate_issuePlace1975646822";
        java.lang.String _cifCreate_expireDate = "_cifCreate_expireDate1175691292";
        java.lang.String _cifCreate_address = "_cifCreate_address-1051840507";
        java.lang.String _cifCreate_country = "_cifCreate_country1334651206";
        java.lang.String _cifCreate_nationality = "_cifCreate_nationality1236218398";
        java.lang.String _cifCreate_language = "_cifCreate_language-435238370";
        java.lang.String _cifCreate_guardian = "_cifCreate_guardian969843176";
        java.lang.String _cifCreate_classification = "_cifCreate_classification-336395946";
        java.lang.String _cifCreate_customerCategory = "_cifCreate_customerCategory531022352";
        java.lang.String _cifCreate_chargeGroup = "_cifCreate_chargeGroup-383584352";
        java.lang.String _cifCreate_swiftCode = "_cifCreate_swiftCode1873024511";
        java.lang.String _cifCreate_maker = "_cifCreate_maker-2124220477";
        java.lang.String _cifCreate_checker = "_cifCreate_checker-1207658672";
        javax.xml.ws.Holder<java.lang.String> _cifCreate_resultCode = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _cifCreate_resultDesc = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _cifCreate_customerNo = new javax.xml.ws.Holder<java.lang.String>();
        port.cifCreate(_cifCreate_sourceRef, _cifCreate_brid, _cifCreate_type, _cifCreate_fullName, _cifCreate_shortName, _cifCreate_gender, _cifCreate_dateOfBirth, _cifCreate_isEmployee, _cifCreate_taxCode, _cifCreate_identityType, _cifCreate_identityNumber, _cifCreate_issueDate, _cifCreate_issuePlace, _cifCreate_expireDate, _cifCreate_address, _cifCreate_country, _cifCreate_nationality, _cifCreate_language, _cifCreate_guardian, _cifCreate_classification, _cifCreate_customerCategory, _cifCreate_chargeGroup, _cifCreate_swiftCode, _cifCreate_maker, _cifCreate_checker, _cifCreate_resultCode, _cifCreate_resultDesc, _cifCreate_customerNo);

        System.out.println("cifCreate._cifCreate_resultCode=" + _cifCreate_resultCode.value);
        System.out.println("cifCreate._cifCreate_resultDesc=" + _cifCreate_resultDesc.value);
        System.out.println("cifCreate._cifCreate_customerNo=" + _cifCreate_customerNo.value);

        }
        {
        System.out.println("Invoking coreACSearch...");
        java.lang.String _coreACSearch_pACCLASSTYPE = "_coreACSearch_pACCLASSTYPE-1437815765";
        java.lang.String _coreACSearch_pMAKERID = "_coreACSearch_pMAKERID242686992";
        java.lang.String _coreACSearch_pCHECKERID = "_coreACSearch_pCHECKERID-1725568137";
        com.alsb.CoreACSearchResponse.AccountClassList _coreACSearch__return = port.coreACSearch(_coreACSearch_pACCLASSTYPE, _coreACSearch_pMAKERID, _coreACSearch_pCHECKERID);
        System.out.println("coreACSearch.result=" + _coreACSearch__return);


        }
        {
        System.out.println("Invoking coreUserChangePassword...");
        java.lang.String _coreUserChangePassword_sourceRef = "_coreUserChangePassword_sourceRef643230911";
        java.lang.String _coreUserChangePassword_username = "_coreUserChangePassword_username983829699";
        java.lang.String _coreUserChangePassword_password = "_coreUserChangePassword_password-1573640408";
        java.lang.String _coreUserChangePassword_newPassword = "_coreUserChangePassword_newPassword-404709943";
        java.lang.String _coreUserChangePassword_maker = "_coreUserChangePassword_maker-1069747313";
        java.lang.String _coreUserChangePassword_approver = "_coreUserChangePassword_approver-213829613";
        java.lang.String _coreUserChangePassword__return = port.coreUserChangePassword(_coreUserChangePassword_sourceRef, _coreUserChangePassword_username, _coreUserChangePassword_password, _coreUserChangePassword_newPassword, _coreUserChangePassword_maker, _coreUserChangePassword_approver);
        System.out.println("coreUserChangePassword.result=" + _coreUserChangePassword__return);


        }
        {
        System.out.println("Invoking coreExchangeRateTypeSearch...");
        java.lang.String _coreExchangeRateTypeSearch_pMAKER = "_coreExchangeRateTypeSearch_pMAKER1148441535";
        java.lang.String _coreExchangeRateTypeSearch_pCHECKER = "_coreExchangeRateTypeSearch_pCHECKER-1288837174";
        com.alsb.CoreExchangeRateTypeSearchResponse.ExchangeRateTypeList _coreExchangeRateTypeSearch__return = port.coreExchangeRateTypeSearch(_coreExchangeRateTypeSearch_pMAKER, _coreExchangeRateTypeSearch_pCHECKER);
        System.out.println("coreExchangeRateTypeSearch.result=" + _coreExchangeRateTypeSearch__return);


        }
        {
        System.out.println("Invoking coreUserLogin...");
        java.lang.String _coreUserLogin_username = "_coreUserLogin_username-311885819";
        java.lang.String _coreUserLogin_password = "_coreUserLogin_password923889129";
        java.lang.String _coreUserLogin__return = port.coreUserLogin(_coreUserLogin_username, _coreUserLogin_password);
        System.out.println("coreUserLogin.result=" + _coreUserLogin__return);


        }
        {
        System.out.println("Invoking coreACClassTransfer...");
        java.lang.String _coreACClassTransfer_pMSGID = "_coreACClassTransfer_pMSGID-1667306470";
        java.lang.String _coreACClassTransfer_pACCLASSFROM = "_coreACClassTransfer_pACCLASSFROM18247902";
        java.lang.String _coreACClassTransfer_pACCLASSTO = "_coreACClassTransfer_pACCLASSTO-1810743679";
        java.lang.String _coreACClassTransfer_pOPERATIONUSER = "_coreACClassTransfer_pOPERATIONUSER529709540";
        java.lang.String _coreACClassTransfer_pMAKERID = "_coreACClassTransfer_pMAKERID2099498736";
        java.lang.String _coreACClassTransfer_pCHECKERID = "_coreACClassTransfer_pCHECKERID1496627855";
        java.lang.String _coreACClassTransfer__return = port.coreACClassTransfer(_coreACClassTransfer_pMSGID, _coreACClassTransfer_pACCLASSFROM, _coreACClassTransfer_pACCLASSTO, _coreACClassTransfer_pOPERATIONUSER, _coreACClassTransfer_pMAKERID, _coreACClassTransfer_pCHECKERID);
        System.out.println("coreACClassTransfer.result=" + _coreACClassTransfer__return);


        }
        {
        System.out.println("Invoking coreUserCreate...");
        java.lang.String _coreUserCreate_sourceRef = "_coreUserCreate_sourceRef2002662587";
        java.lang.String _coreUserCreate_username = "_coreUserCreate_username-1668082326";
        java.lang.String _coreUserCreate_password = "_coreUserCreate_password88677456";
        java.lang.String _coreUserCreate_name = "_coreUserCreate_name-1930586723";
        java.lang.String _coreUserCreate_userID = "_coreUserCreate_userID1997181774";
        java.lang.String _coreUserCreate_brid = "_coreUserCreate_brid-1083493152";
        java.lang.String _coreUserCreate_customerNo = "_coreUserCreate_customerNo-1048326975";
        java.lang.String _coreUserCreate_maker = "_coreUserCreate_maker1645368409";
        java.lang.String _coreUserCreate_approver = "_coreUserCreate_approver757341050";
        java.lang.String _coreUserCreate__return = port.coreUserCreate(_coreUserCreate_sourceRef, _coreUserCreate_username, _coreUserCreate_password, _coreUserCreate_name, _coreUserCreate_userID, _coreUserCreate_brid, _coreUserCreate_customerNo, _coreUserCreate_maker, _coreUserCreate_approver);
        System.out.println("coreUserCreate.result=" + _coreUserCreate__return);


        }
        {
        System.out.println("Invoking coreExchangeRateSearch...");
        java.lang.String _coreExchangeRateSearch_pBRANCH = "_coreExchangeRateSearch_pBRANCH-50564075";
        java.lang.String _coreExchangeRateSearch_pCCY1 = "_coreExchangeRateSearch_pCCY12046105258";
        java.lang.String _coreExchangeRateSearch_pCCY2 = "_coreExchangeRateSearch_pCCY2-893170126";
        java.lang.String _coreExchangeRateSearch_pMAKER = "_coreExchangeRateSearch_pMAKER-534799067";
        java.lang.String _coreExchangeRateSearch_pCHECKER = "_coreExchangeRateSearch_pCHECKER1513919998";
        com.alsb.CoreExchangeRateSearchResponse.ExchangeRateList _coreExchangeRateSearch__return = port.coreExchangeRateSearch(_coreExchangeRateSearch_pBRANCH, _coreExchangeRateSearch_pCCY1, _coreExchangeRateSearch_pCCY2, _coreExchangeRateSearch_pMAKER, _coreExchangeRateSearch_pCHECKER);
        System.out.println("coreExchangeRateSearch.result=" + _coreExchangeRateSearch__return);


        }
        {
        System.out.println("Invoking cifUpdate...");
        java.lang.String _cifUpdate_sourceRef = "_cifUpdate_sourceRef-1978219020";
        java.lang.String _cifUpdate_cifCode = "_cifUpdate_cifCode331253904";
        java.lang.String _cifUpdate_brid = "_cifUpdate_brid1635143971";
        java.lang.String _cifUpdate_type = "_cifUpdate_type-594457688";
        java.lang.String _cifUpdate_fullName = "_cifUpdate_fullName-203232787";
        java.lang.String _cifUpdate_shortName = "_cifUpdate_shortName-1196451616";
        java.lang.String _cifUpdate_gender = "_cifUpdate_gender-80276554";
        java.lang.String _cifUpdate_dateOfBirth = "_cifUpdate_dateOfBirth-1796688279";
        java.lang.String _cifUpdate_isEmployee = "_cifUpdate_isEmployee1043201391";
        java.lang.String _cifUpdate_taxCode = "_cifUpdate_taxCode1238569967";
        java.lang.String _cifUpdate_identityType = "_cifUpdate_identityType-2045623464";
        java.lang.String _cifUpdate_identityNumber = "_cifUpdate_identityNumber26958169";
        java.lang.String _cifUpdate_issueDate = "_cifUpdate_issueDate1337519425";
        java.lang.String _cifUpdate_issuePlace = "_cifUpdate_issuePlace-2137973125";
        java.lang.String _cifUpdate_expireDate = "_cifUpdate_expireDate-1384233033";
        java.lang.String _cifUpdate_address1 = "_cifUpdate_address1-755552768";
        java.lang.String _cifUpdate_country = "_cifUpdate_country1089642684";
        java.lang.String _cifUpdate_nationality = "_cifUpdate_nationality-1630014713";
        java.lang.String _cifUpdate_language = "_cifUpdate_language351208704";
        java.lang.String _cifUpdate_guardian = "_cifUpdate_guardian-803549104";
        java.lang.String _cifUpdate_classification = "_cifUpdate_classification-742987599";
        java.lang.String _cifUpdate_customerCategory = "_cifUpdate_customerCategory-398954258";
        java.lang.String _cifUpdate_chargeGroup = "_cifUpdate_chargeGroup-805650592";
        java.lang.String _cifUpdate_swiftCode = "_cifUpdate_swiftCode1489171925";
        java.lang.String _cifUpdate_reuterCode = "_cifUpdate_reuterCode1288894602";
        java.lang.String _cifUpdate_citadCode = "_cifUpdate_citadCode693373115";
        java.lang.String _cifUpdate_giinCode = "_cifUpdate_giinCode-2081738041";
        java.lang.String _cifUpdate_maker = "_cifUpdate_maker-333732822";
        java.lang.String _cifUpdate_checker = "_cifUpdate_checker-1661612625";
        java.lang.String _cifUpdate__return = port.cifUpdate(_cifUpdate_sourceRef, _cifUpdate_cifCode, _cifUpdate_brid, _cifUpdate_type, _cifUpdate_fullName, _cifUpdate_shortName, _cifUpdate_gender, _cifUpdate_dateOfBirth, _cifUpdate_isEmployee, _cifUpdate_taxCode, _cifUpdate_identityType, _cifUpdate_identityNumber, _cifUpdate_issueDate, _cifUpdate_issuePlace, _cifUpdate_expireDate, _cifUpdate_address1, _cifUpdate_country, _cifUpdate_nationality, _cifUpdate_language, _cifUpdate_guardian, _cifUpdate_classification, _cifUpdate_customerCategory, _cifUpdate_chargeGroup, _cifUpdate_swiftCode, _cifUpdate_reuterCode, _cifUpdate_citadCode, _cifUpdate_giinCode, _cifUpdate_maker, _cifUpdate_checker);
        System.out.println("cifUpdate.result=" + _cifUpdate__return);


        }
        {
        System.out.println("Invoking coreExchangeRateUpdate...");
        java.lang.String _coreExchangeRateUpdate_sourceRef = "_coreExchangeRateUpdate_sourceRef726440375";
        java.lang.String _coreExchangeRateUpdate_brid = "_coreExchangeRateUpdate_brid-1411259666";
        java.lang.String _coreExchangeRateUpdate_ccy1 = "_coreExchangeRateUpdate_ccy1130669230";
        java.lang.String _coreExchangeRateUpdate_ccy2 = "_coreExchangeRateUpdate_ccy2-1875564246";
        java.lang.String _coreExchangeRateUpdate_exchangeRateTypeCode = "_coreExchangeRateUpdate_exchangeRateTypeCode-1025764158";
        java.lang.String _coreExchangeRateUpdate_averageRate = "_coreExchangeRateUpdate_averageRate899868571";
        java.lang.String _coreExchangeRateUpdate_buyAmplitude = "_coreExchangeRateUpdate_buyAmplitude1685693304";
        java.lang.String _coreExchangeRateUpdate_sellAmplitude = "_coreExchangeRateUpdate_sellAmplitude1924530061";
        java.lang.String _coreExchangeRateUpdate_buyRate = "_coreExchangeRateUpdate_buyRate516094054";
        java.lang.String _coreExchangeRateUpdate_sellRate = "_coreExchangeRateUpdate_sellRate-460736221";
        java.lang.String _coreExchangeRateUpdate_effectDate = "_coreExchangeRateUpdate_effectDate159891335";
        java.lang.String _coreExchangeRateUpdate_maker = "_coreExchangeRateUpdate_maker-1198423278";
        java.lang.String _coreExchangeRateUpdate_approver = "_coreExchangeRateUpdate_approver-1667630551";
        java.lang.String _coreExchangeRateUpdate__return = port.coreExchangeRateUpdate(_coreExchangeRateUpdate_sourceRef, _coreExchangeRateUpdate_brid, _coreExchangeRateUpdate_ccy1, _coreExchangeRateUpdate_ccy2, _coreExchangeRateUpdate_exchangeRateTypeCode, _coreExchangeRateUpdate_averageRate, _coreExchangeRateUpdate_buyAmplitude, _coreExchangeRateUpdate_sellAmplitude, _coreExchangeRateUpdate_buyRate, _coreExchangeRateUpdate_sellRate, _coreExchangeRateUpdate_effectDate, _coreExchangeRateUpdate_maker, _coreExchangeRateUpdate_approver);
        System.out.println("coreExchangeRateUpdate.result=" + _coreExchangeRateUpdate__return);


        }
        {
        System.out.println("Invoking coreInterestRateCodeGet...");
        java.lang.String _coreInterestRateCodeGet_pPARAMCODE = "_coreInterestRateCodeGet_pPARAMCODE1046462768";
        java.lang.String _coreInterestRateCodeGet_pCCY = "_coreInterestRateCodeGet_pCCY1461543486";
        java.lang.String _coreInterestRateCodeGet_pMAKER = "_coreInterestRateCodeGet_pMAKER-1661064188";
        java.lang.String _coreInterestRateCodeGet_pCHECKER = "_coreInterestRateCodeGet_pCHECKER-553357022";
        com.alsb.CoreInterestRateCodeGetResponse.InterestRateCodeList _coreInterestRateCodeGet__return = port.coreInterestRateCodeGet(_coreInterestRateCodeGet_pPARAMCODE, _coreInterestRateCodeGet_pCCY, _coreInterestRateCodeGet_pMAKER, _coreInterestRateCodeGet_pCHECKER);
        System.out.println("coreInterestRateCodeGet.result=" + _coreInterestRateCodeGet__return);


        }

        System.exit(0);
    }

}
