package com.alsb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-07T23:26:35.714+07:00
 * Generated source version: 3.1.11
 * 
 */
@javax.jws.WebService(targetNamespace = "http://www.alsb.com/", name = "WebService")
@XmlSeeAlso({ObjectFactory.class})
public interface WebService {

    @WebMethod(operationName = "CoreACInterestRateUpdate", action = "http://www.alsb.com/WebService/CoreACInterestRateUpdate")
    @RequestWrapper(localName = "CoreACInterestRateUpdate", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACInterestRateUpdate")
    @ResponseWrapper(localName = "CoreACInterestRateUpdateResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACInterestRateUpdateResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String coreACInterestRateUpdate(
        @WebParam(name = "SourceRef", targetNamespace = "")
        java.lang.String sourceRef,
        @WebParam(name = "AccountClass", targetNamespace = "")
        java.lang.String accountClass,
        @WebParam(name = "CCYCD", targetNamespace = "")
        java.lang.String ccycd,
        @WebParam(name = "EffectiveDate", targetNamespace = "")
        java.lang.String effectiveDate,
        @WebParam(name = "BRID", targetNamespace = "")
        java.lang.String brid,
        @WebParam(name = "InterestRateList", targetNamespace = "")
        com.alsb.CoreACInterestRateUpdate.InterestRateList interestRateList,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Approver", targetNamespace = "")
        java.lang.String approver
    );

    @WebMethod(operationName = "LDAPUserSearch", action = "http://www.alsb.com/WebService/LDAPUserSearch")
    @RequestWrapper(localName = "LDAPUserSearch", targetNamespace = "http://www.alsb.com/", className = "com.alsb.LDAPUserSearch")
    @ResponseWrapper(localName = "LDAPUserSearchResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.LDAPUserSearchResponse")
    @WebResult(name = "UserList", targetNamespace = "")
    public com.alsb.LDAPUserSearchResponse.UserList ldapUserSearch(
        @WebParam(name = "UserID", targetNamespace = "")
        java.lang.String userID,
        @WebParam(name = "Name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "Username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "Email", targetNamespace = "")
        java.lang.String email
    );

    @WebMethod(operationName = "CoreUsernameVerify", action = "http://www.alsb.com/WebService/CoreUsernameVerify")
    @RequestWrapper(localName = "CoreUsernameVerify", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUsernameVerify")
    @ResponseWrapper(localName = "CoreUsernameVerifyResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUsernameVerifyResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String coreUsernameVerify(
        @WebParam(name = "Username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Approver", targetNamespace = "")
        java.lang.String approver
    );

    @WebMethod(operationName = "CoreUserResetPassword", action = "http://www.alsb.com/WebService/CoreUserResetPassword")
    @RequestWrapper(localName = "CoreUserResetPassword", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserResetPassword")
    @ResponseWrapper(localName = "CoreUserResetPasswordResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserResetPasswordResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String coreUserResetPassword(
        @WebParam(name = "SourceRef", targetNamespace = "")
        java.lang.String sourceRef,
        @WebParam(name = "Username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "NewPassword", targetNamespace = "")
        java.lang.String newPassword,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Approver", targetNamespace = "")
        java.lang.String approver
    );

    @WebMethod(operationName = "CoreACParamsGet", action = "http://www.alsb.com/WebService/CoreACParamsGet")
    @RequestWrapper(localName = "CoreACParamsGet", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACParamsGet")
    @ResponseWrapper(localName = "CoreACParamsGetResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACParamsGetResponse")
    @WebResult(name = "ParameterList", targetNamespace = "")
    public com.alsb.CoreACParamsGetResponse.ParameterList coreACParamsGet(
        @WebParam(name = "P_ACCLASS", targetNamespace = "")
        java.lang.String pACCLASS,
        @WebParam(name = "P_MAKERID", targetNamespace = "")
        java.lang.String pMAKERID,
        @WebParam(name = "P_CHECKERID", targetNamespace = "")
        java.lang.String pCHECKERID
    );

    @WebMethod(operationName = "CoreACInterestRateSearch", action = "http://www.alsb.com/WebService/CoreACInterestRateSearch")
    @RequestWrapper(localName = "CoreACInterestRateSearch", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACInterestRateSearch")
    @ResponseWrapper(localName = "CoreACInterestRateSearchResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACInterestRateSearchResponse")
    @WebResult(name = "InterestRateList", targetNamespace = "")
    public com.alsb.CoreACInterestRateSearchResponse.InterestRateList coreACInterestRateSearch(
        @WebParam(name = "P_AC_CLASS", targetNamespace = "")
        java.lang.String pACCLASS,
        @WebParam(name = "P_CCY", targetNamespace = "")
        java.lang.String pCCY,
        @WebParam(name = "P_EFFECTIVE_DATE", targetNamespace = "")
        java.lang.String pEFFECTIVEDATE,
        @WebParam(name = "P_BRANCH", targetNamespace = "")
        java.lang.String pBRANCH,
        @WebParam(name = "P_MAKER", targetNamespace = "")
        java.lang.String pMAKER,
        @WebParam(name = "P_CHECKER", targetNamespace = "")
        java.lang.String pCHECKER
    );

    @WebMethod(operationName = "CIFCreate", action = "http://www.alsb.com/WebService/CIFCreate")
    @RequestWrapper(localName = "CIFCreate", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CIFCreate")
    @ResponseWrapper(localName = "CIFCreateResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CIFCreateResponse")
    public void cifCreate(
        @WebParam(name = "SourceRef", targetNamespace = "")
        java.lang.String sourceRef,
        @WebParam(name = "BRID", targetNamespace = "")
        java.lang.String brid,
        @WebParam(name = "Type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "FullName", targetNamespace = "")
        java.lang.String fullName,
        @WebParam(name = "ShortName", targetNamespace = "")
        java.lang.String shortName,
        @WebParam(name = "Gender", targetNamespace = "")
        java.lang.String gender,
        @WebParam(name = "DateOfBirth", targetNamespace = "")
        java.lang.String dateOfBirth,
        @WebParam(name = "IsEmployee", targetNamespace = "")
        java.lang.String isEmployee,
        @WebParam(name = "TaxCode", targetNamespace = "")
        java.lang.String taxCode,
        @WebParam(name = "IdentityType", targetNamespace = "")
        java.lang.String identityType,
        @WebParam(name = "IdentityNumber", targetNamespace = "")
        java.lang.String identityNumber,
        @WebParam(name = "IssueDate", targetNamespace = "")
        java.lang.String issueDate,
        @WebParam(name = "IssuePlace", targetNamespace = "")
        java.lang.String issuePlace,
        @WebParam(name = "ExpireDate", targetNamespace = "")
        java.lang.String expireDate,
        @WebParam(name = "Address", targetNamespace = "")
        java.lang.String address,
        @WebParam(name = "Country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "Nationality", targetNamespace = "")
        java.lang.String nationality,
        @WebParam(name = "Language", targetNamespace = "")
        java.lang.String language,
        @WebParam(name = "Guardian", targetNamespace = "")
        java.lang.String guardian,
        @WebParam(name = "Classification", targetNamespace = "")
        java.lang.String classification,
        @WebParam(name = "CustomerCategory", targetNamespace = "")
        java.lang.String customerCategory,
        @WebParam(name = "ChargeGroup", targetNamespace = "")
        java.lang.String chargeGroup,
        @WebParam(name = "SWIFTCode", targetNamespace = "")
        java.lang.String swiftCode,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Checker", targetNamespace = "")
        java.lang.String checker,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResultDesc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> resultDesc,
        @WebParam(mode = WebParam.Mode.OUT, name = "CustomerNo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> customerNo
    );

    @WebMethod(operationName = "CoreACSearch", action = "http://www.alsb.com/WebService/CoreACSearch")
    @RequestWrapper(localName = "CoreACSearch", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACSearch")
    @ResponseWrapper(localName = "CoreACSearchResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACSearchResponse")
    @WebResult(name = "AccountClassList", targetNamespace = "")
    public com.alsb.CoreACSearchResponse.AccountClassList coreACSearch(
        @WebParam(name = "P_AC_CLASS_TYPE", targetNamespace = "")
        java.lang.String pACCLASSTYPE,
        @WebParam(name = "P_MAKERID", targetNamespace = "")
        java.lang.String pMAKERID,
        @WebParam(name = "P_CHECKERID", targetNamespace = "")
        java.lang.String pCHECKERID
    );

    @WebMethod(operationName = "CoreUserChangePassword", action = "http://www.alsb.com/WebService/CoreUserChangePassword")
    @RequestWrapper(localName = "CoreUserChangePassword", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserChangePassword")
    @ResponseWrapper(localName = "CoreUserChangePasswordResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserChangePasswordResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String coreUserChangePassword(
        @WebParam(name = "SourceRef", targetNamespace = "")
        java.lang.String sourceRef,
        @WebParam(name = "Username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "NewPassword", targetNamespace = "")
        java.lang.String newPassword,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Approver", targetNamespace = "")
        java.lang.String approver
    );

    @WebMethod(operationName = "CoreExchangeRateTypeSearch", action = "http://www.alsb.com/WebService/CoreExchangeRateTypeSearch")
    @RequestWrapper(localName = "CoreExchangeRateTypeSearch", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreExchangeRateTypeSearch")
    @ResponseWrapper(localName = "CoreExchangeRateTypeSearchResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreExchangeRateTypeSearchResponse")
    @WebResult(name = "ExchangeRateTypeList", targetNamespace = "")
    public com.alsb.CoreExchangeRateTypeSearchResponse.ExchangeRateTypeList coreExchangeRateTypeSearch(
        @WebParam(name = "P_MAKER", targetNamespace = "")
        java.lang.String pMAKER,
        @WebParam(name = "P_CHECKER", targetNamespace = "")
        java.lang.String pCHECKER
    );

    @WebMethod(operationName = "CoreUserLogin", action = "http://www.alsb.com/WebService/CoreUserLogin")
    @RequestWrapper(localName = "CoreUserLogin", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserLogin")
    @ResponseWrapper(localName = "CoreUserLoginResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserLoginResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String coreUserLogin(
        @WebParam(name = "Username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod(operationName = "CoreACClassTransfer", action = "http://www.alsb.com/WebService/CoreACClassTransfer")
    @RequestWrapper(localName = "CoreACClassTransfer", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACClassTransfer")
    @ResponseWrapper(localName = "CoreACClassTransferResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreACClassTransferResponse")
    @WebResult(name = "RES", targetNamespace = "")
    public java.lang.String coreACClassTransfer(
        @WebParam(name = "P_MSGID", targetNamespace = "")
        java.lang.String pMSGID,
        @WebParam(name = "P_ACCLASSFROM", targetNamespace = "")
        java.lang.String pACCLASSFROM,
        @WebParam(name = "P_ACCLASSTO", targetNamespace = "")
        java.lang.String pACCLASSTO,
        @WebParam(name = "P_OPERATIONUSER", targetNamespace = "")
        java.lang.String pOPERATIONUSER,
        @WebParam(name = "P_MAKERID", targetNamespace = "")
        java.lang.String pMAKERID,
        @WebParam(name = "P_CHECKERID", targetNamespace = "")
        java.lang.String pCHECKERID
    );

    @WebMethod(operationName = "CoreUserCreate", action = "http://www.alsb.com/WebService/CoreUserCreate")
    @RequestWrapper(localName = "CoreUserCreate", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserCreate")
    @ResponseWrapper(localName = "CoreUserCreateResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreUserCreateResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String coreUserCreate(
        @WebParam(name = "SourceRef", targetNamespace = "")
        java.lang.String sourceRef,
        @WebParam(name = "Username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "Name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "UserID", targetNamespace = "")
        java.lang.String userID,
        @WebParam(name = "BRID", targetNamespace = "")
        java.lang.String brid,
        @WebParam(name = "CustomerNo", targetNamespace = "")
        java.lang.String customerNo,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Approver", targetNamespace = "")
        java.lang.String approver
    );

    @WebMethod(operationName = "CoreExchangeRateSearch", action = "http://www.alsb.com/WebService/CoreExchangeRateSearch")
    @RequestWrapper(localName = "CoreExchangeRateSearch", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreExchangeRateSearch")
    @ResponseWrapper(localName = "CoreExchangeRateSearchResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreExchangeRateSearchResponse")
    @WebResult(name = "ExchangeRateList", targetNamespace = "")
    public com.alsb.CoreExchangeRateSearchResponse.ExchangeRateList coreExchangeRateSearch(
        @WebParam(name = "P_BRANCH", targetNamespace = "")
        java.lang.String pBRANCH,
        @WebParam(name = "P_CCY1", targetNamespace = "")
        java.lang.String pCCY1,
        @WebParam(name = "P_CCY2", targetNamespace = "")
        java.lang.String pCCY2,
        @WebParam(name = "P_MAKER", targetNamespace = "")
        java.lang.String pMAKER,
        @WebParam(name = "P_CHECKER", targetNamespace = "")
        java.lang.String pCHECKER
    );

    @WebMethod(operationName = "CIFUpdate", action = "http://www.alsb.com/WebService/CIFUpdate")
    @RequestWrapper(localName = "CIFUpdate", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CIFUpdate")
    @ResponseWrapper(localName = "CIFUpdateResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CIFUpdateResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String cifUpdate(
        @WebParam(name = "SourceRef", targetNamespace = "")
        java.lang.String sourceRef,
        @WebParam(name = "CIFCode", targetNamespace = "")
        java.lang.String cifCode,
        @WebParam(name = "BRID", targetNamespace = "")
        java.lang.String brid,
        @WebParam(name = "Type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "FullName", targetNamespace = "")
        java.lang.String fullName,
        @WebParam(name = "ShortName", targetNamespace = "")
        java.lang.String shortName,
        @WebParam(name = "Gender", targetNamespace = "")
        java.lang.String gender,
        @WebParam(name = "DateOfBirth", targetNamespace = "")
        java.lang.String dateOfBirth,
        @WebParam(name = "IsEmployee", targetNamespace = "")
        java.lang.String isEmployee,
        @WebParam(name = "TaxCode", targetNamespace = "")
        java.lang.String taxCode,
        @WebParam(name = "IdentityType", targetNamespace = "")
        java.lang.String identityType,
        @WebParam(name = "IdentityNumber", targetNamespace = "")
        java.lang.String identityNumber,
        @WebParam(name = "IssueDate", targetNamespace = "")
        java.lang.String issueDate,
        @WebParam(name = "IssuePlace", targetNamespace = "")
        java.lang.String issuePlace,
        @WebParam(name = "ExpireDate", targetNamespace = "")
        java.lang.String expireDate,
        @WebParam(name = "Address1", targetNamespace = "")
        java.lang.String address1,
        @WebParam(name = "Country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "Nationality", targetNamespace = "")
        java.lang.String nationality,
        @WebParam(name = "Language", targetNamespace = "")
        java.lang.String language,
        @WebParam(name = "Guardian", targetNamespace = "")
        java.lang.String guardian,
        @WebParam(name = "Classification", targetNamespace = "")
        java.lang.String classification,
        @WebParam(name = "CustomerCategory", targetNamespace = "")
        java.lang.String customerCategory,
        @WebParam(name = "ChargeGroup", targetNamespace = "")
        java.lang.String chargeGroup,
        @WebParam(name = "SWIFTCode", targetNamespace = "")
        java.lang.String swiftCode,
        @WebParam(name = "REUTERCode", targetNamespace = "")
        java.lang.String reuterCode,
        @WebParam(name = "CITADCode", targetNamespace = "")
        java.lang.String citadCode,
        @WebParam(name = "GIINCode", targetNamespace = "")
        java.lang.String giinCode,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Checker", targetNamespace = "")
        java.lang.String checker
    );

    @WebMethod(operationName = "CoreExchangeRateUpdate", action = "http://www.alsb.com/WebService/CoreExchangeRateUpdate")
    @RequestWrapper(localName = "CoreExchangeRateUpdate", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreExchangeRateUpdate")
    @ResponseWrapper(localName = "CoreExchangeRateUpdateResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreExchangeRateUpdateResponse")
    @WebResult(name = "ErrorCode", targetNamespace = "")
    public java.lang.String coreExchangeRateUpdate(
        @WebParam(name = "SourceRef", targetNamespace = "")
        java.lang.String sourceRef,
        @WebParam(name = "BRID", targetNamespace = "")
        java.lang.String brid,
        @WebParam(name = "CCY1", targetNamespace = "")
        java.lang.String ccy1,
        @WebParam(name = "CCY2", targetNamespace = "")
        java.lang.String ccy2,
        @WebParam(name = "ExchangeRateTypeCode", targetNamespace = "")
        java.lang.String exchangeRateTypeCode,
        @WebParam(name = "AverageRate", targetNamespace = "")
        java.lang.String averageRate,
        @WebParam(name = "BuyAmplitude", targetNamespace = "")
        java.lang.String buyAmplitude,
        @WebParam(name = "SellAmplitude", targetNamespace = "")
        java.lang.String sellAmplitude,
        @WebParam(name = "BuyRate", targetNamespace = "")
        java.lang.String buyRate,
        @WebParam(name = "SellRate", targetNamespace = "")
        java.lang.String sellRate,
        @WebParam(name = "EffectDate", targetNamespace = "")
        java.lang.String effectDate,
        @WebParam(name = "Maker", targetNamespace = "")
        java.lang.String maker,
        @WebParam(name = "Approver", targetNamespace = "")
        java.lang.String approver
    );

    @WebMethod(operationName = "CoreInterestRateCodeGet", action = "http://www.alsb.com/WebService/CoreInterestRateCodeGet")
    @RequestWrapper(localName = "CoreInterestRateCodeGet", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreInterestRateCodeGet")
    @ResponseWrapper(localName = "CoreInterestRateCodeGetResponse", targetNamespace = "http://www.alsb.com/", className = "com.alsb.CoreInterestRateCodeGetResponse")
    @WebResult(name = "InterestRateCodeList", targetNamespace = "")
    public com.alsb.CoreInterestRateCodeGetResponse.InterestRateCodeList coreInterestRateCodeGet(
        @WebParam(name = "P_PARAMCODE", targetNamespace = "")
        java.lang.String pPARAMCODE,
        @WebParam(name = "P_CCY", targetNamespace = "")
        java.lang.String pCCY,
        @WebParam(name = "P_MAKER", targetNamespace = "")
        java.lang.String pMAKER,
        @WebParam(name = "P_CHECKER", targetNamespace = "")
        java.lang.String pCHECKER
    );
}
